// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Binding.Views;
using Weather.Converters;
using Weather.iOS.Converters;

namespace Weather.iOS.Views.Cells
{
    public partial class ForecastCell : MvxTableViewCell
    {
        public const string CellId = "ForecastCell";

        public ForecastCell(IntPtr handle) : base(handle)
        {
            this.DelayBind(() =>
            {
                var set = this.CreateBindingSet<ForecastCell, Models.Weather>();
                set.Bind(this.DayName).To(m => m.Date).WithConversion<DayNameConverter>();
                set.Bind(this.Temps).To(m => m).WithConversion<TempsCombinerConverter>();
                set.Bind(this.WeatherIcon).For(v => v.Image).To(m => m.Icon).WithConversion<IconsConverter>();
                set.Apply();
            });
        }
    }
}
