// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Views;
using UIKit;
using Weather.Converters;
using Weather.iOS.Converters;
using Weather.iOS.Views.ViewSources;
using Weather.ViewModels;

namespace Weather.iOS.Views
{
    [MvxFromStoryboard]
    public partial class HomeView : MvxViewController<HomeViewModel>
    {
        private ForecastTableViewSource _forecastTableViewSource;

        public HomeView(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<HomeView, HomeViewModel>();
            set.Bind(this.IsMockSwitch).To(vm => vm.IsMock);
            set.Bind(this.LocationName).To(vm => vm.CityName);
            set.Bind(this.CurrentTemp).To(vm => vm.CurrentTemperature).WithConversion<TempConverter>();
            set.Bind(this.MinTemp).To(vm => vm.MinTemperature).WithConversion<TempConverter>();
            set.Bind(this.MaxTemp).To(vm => vm.MaxTemperature).WithConversion<TempConverter>();
            set.Bind(this.CurrentWeatherImage).For(v => v.Image).To(vm => vm.CurrentImage).WithConversion<IconsConverter>();
            set.Bind(this.CurrentWeatherCondition).To(vm => vm.Text);
            set.Bind(this.PoweredBy).To(vm => vm.PoweredBy);

            _forecastTableViewSource = new ForecastTableViewSource(this.ForecastTable);
            set.Bind(_forecastTableViewSource).To(vm => vm.UpcomingWeathers);

            set.Bind(this.ReloadButton).To(vm => vm.LoadDataCommand);
            set.Bind(this.ChangeCity).To(vm => vm.LoadCityCommand);

            set.Apply();

            this.ForecastTable.Source = _forecastTableViewSource;
            this.ForecastTable.ReloadData();
            this.ForecastTable.TableFooterView = new UIView();
        }
    }
}
